// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
// package startexercicio24;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

// import java.lang.reflect.Method;

// class AppTest {
//     @Test void appHasAGreeting() {
//         App classUnderTest = new App();
//         assertNotNull(MethodUnderTest.main(), "app should have a greeting");
//     }
// }
